%%{init: {"themeCSS": ".relation { stroke: transparent !important; }"}}%%
classDiagram
  direction TB
  class class_1["InvalidRelativePathError"] {
    +constructor()
  }
  class class_2["PathOutsideAllowlistError"] {
    +constructor()
  }
  class_1 -- class_2
