graph TD
    W[recordUpdateMetric] --> R[readMetrics]
    R --> M[metricsPath]
    W --> P[preserveCorruptLedger]
    P --> B[backupRelPath]
    W --> WR[writeMetrics]
    S[snapshotMetrics] --> R
    S --> WC[warnCorruptOnRead]
    L[listUpdateMetrics] --> R
    L --> WC2[warnCorruptOnRead]
    C[clearMetricsForTests] --> WR
    WR --> SA[safeIo.writeTextAtomic]
    M --> SR[safeIo.resolveAndValidate]
    P --> SR
