%%{init: {"themeCSS": ".relation { stroke: transparent !important; }"}}%%
classDiagram
  direction TB
  class class_1["UnknownPresetError"] {
    +constructor()
  }
  class class_2["ReadmeExportError"] {
    +constructor()
  }
  class_1 -- class_2
