%%{init: {"themeCSS": ".relation { stroke: transparent !important; }"}}%%
classDiagram
  direction TB
  class class_1["AnchorParseError"] {
    +constructor()
  }
  class class_2["MockLlm"] {
    +generate()
  }
  class class_3["FailingMockLlm"] {
    +calledModuleIds()
    +generate()
  }
  class class_4["ValidMockLlm"] {
    +calledModuleIds()
    +constructor()
    +generate()
  }
  class class_5["FifteenNodeLlm"] {
    +generate()
  }
  class class_6["ModuleDiagramMockLlm"] {
    +generate()
  }
  class class_7["ProgrammableMockLlm"] {
    +generate()
  }
  class class_8["MockLlm"] {
    +generate()
  }
  class class_9["OneModuleAlwaysTruncatesLlm"] {
    +generate()
  }
  class class_10["RelaxedTopicMockLlm"] {
    +generate()
  }
  class class_11["Stage5MockLlm"] {
    +generate()
  }
  class class_12["TopicMockLlm"] {
    +generate()
  }
  class class_13["OneModuleMockLlm"] {
    +generate()
  }
  class class_14["OneShotMockLlm"] {
    +generate()
  }
  class class_15["ValidMockLlm"] {
    +generate()
  }
  class class_16["SurgicalFlowMockLlm"] {
    +generate()
  }
  class class_17["SurgicalModuleMockLlm"] {
    +generate()
  }
  class class_18["SurgicalTopicMockLlm"] {
    +generate()
  }
  class class_19["TestRoleMockLlm"] {
    +generate()
  }
  class class_20["UnderstandingMockLlm"] {
    +generate()
  }
  class class_21["MockLlm"] {
    +generate()
  }
  class class_22["EmptyPipelineError"] {
    +constructor()
  }
  class class_23["TaskError"] {
    +constructor()
  }
  class class_24["MissingProviderConfigError"] {
    +constructor()
  }
  class class_25["ExportError"] {
    +constructor()
  }
  class class_26["FrontmatterParseError"] {
    +constructor()
  }
  class class_27["FullMockLlm"] {
    +generate()
  }
  class class_28["DuplicateModuleIdError"] {
    +constructor()
  }
  class class_29["ExactPartitionError"] {
    +constructor()
  }
  class class_30["UnknownPresetError"] {
    +constructor()
  }
  class class_31["ReadmeExportError"] {
    +constructor()
  }
  class class_32["InvalidRelativePathError"] {
    +constructor()
  }
  class class_33["PathOutsideAllowlistError"] {
    +constructor()
  }
  class class_34["ViewError"] {
    +constructor()
  }
  class_1 -- class_2
  class_2 -- class_3
  class_3 -- class_4
  class_4 -- class_5
  class_5 -- class_6
  class_6 -- class_7
  class_7 -- class_8
  class_8 -- class_9
  class_9 -- class_10
  class_10 -- class_11
  class_11 -- class_12
  class_12 -- class_13
  class_13 -- class_14
  class_14 -- class_15
  class_15 -- class_16
  class_16 -- class_17
  class_17 -- class_18
  class_18 -- class_19
  class_19 -- class_20
  class_20 -- class_21
  class_21 -- class_22
  class_22 -- class_23
  class_23 -- class_24
  class_24 -- class_25
  class_25 -- class_26
  class_26 -- class_27
  class_27 -- class_28
  class_28 -- class_29
  class_29 -- class_30
  class_30 -- class_31
  class_31 -- class_32
  class_32 -- class_33
  class_33 -- class_34
