%%{init: {"themeCSS": ".relation { stroke: transparent !important; }"}}%%
classDiagram
  direction TB
  class class_1["OneModuleAlwaysTruncatesLlm"] {
    +generate()
  }
  class class_2["RelaxedTopicMockLlm"] {
    +generate()
  }
  class class_3["Stage5MockLlm"] {
    +generate()
  }
  class class_4["TopicMockLlm"] {
    +generate()
  }
  class class_5["OneModuleMockLlm"] {
    +generate()
  }
  class class_6["OneShotMockLlm"] {
    +generate()
  }
  class class_7["ValidMockLlm"] {
    +generate()
  }
  class class_8["SurgicalFlowMockLlm"] {
    +generate()
  }
  class class_9["SurgicalModuleMockLlm"] {
    +generate()
  }
  class class_10["SurgicalTopicMockLlm"] {
    +generate()
  }
  class class_11["MockLlm"] {
    +generate()
  }
  class_1 -- class_2
  class_2 -- class_3
  class_3 -- class_4
  class_4 -- class_5
  class_5 -- class_6
  class_6 -- class_7
  class_7 -- class_8
  class_8 -- class_9
  class_9 -- class_10
  class_10 -- class_11
