%%{init: {"themeCSS": ".relation { stroke: transparent !important; }"}}%%
classDiagram
  direction TB
  class class_1["MockLlm"] {
    +generate()
  }
  class class_2["FailingMockLlm"] {
    +calledModuleIds()
    +generate()
  }
  class class_3["ValidMockLlm"] {
    +calledModuleIds()
    +constructor()
    +generate()
  }
  class class_4["FifteenNodeLlm"] {
    +generate()
  }
  class class_5["ModuleDiagramMockLlm"] {
    +generate()
  }
  class class_6["ProgrammableMockLlm"] {
    +generate()
  }
  class class_7["MockLlm"] {
    +generate()
  }
  class_1 -- class_2
  class_2 -- class_3
  class_3 -- class_4
  class_4 -- class_5
  class_5 -- class_6
  class_6 -- class_7
