%%{init: {"themeCSS": ".relation { stroke: transparent !important; }"}}%%
classDiagram
  direction TB
  class class_1["Mode"] {
  }
  class class_2["Server"] {
    +addr()
    +dispatch()
    +handle()
    +listen()
    +process()
    +Server()
    +start()
  }
  class_1 -- class_2
