flowchart LR
  n0[Entry: cli-src-01] --> n1[commands]
  n1[commands] --> n2[core-src-01]
  n2[core-src-01] --> n3[core-src-02]
  n3[core-src-02] --> n4[core-src-03]
  n4[core-src-03] --> n5[core-src-04]
  n5[core-src-04] --> n6[core-src-06]
  n6[core-src-06] --> n7[core-src-05 - persists]
