%%{init: {"themeCSS": ".relation { stroke: transparent !important; }"}}%%
classDiagram
  direction TB
  class class_1["AnthropicAdapter"] {
    +constructor()
    +generate()
  }
  class class_2["LlmTimeoutError"] {
    +constructor()
  }
  class class_3["LlmRequestError"] {
    +constructor()
  }
  class class_4["MissingApiKeyError"] {
    +constructor()
  }
  class class_5["OpenAiCompatAdapter"] {
    +constructor()
    +generate()
  }
  class_1 -- class_2
  class_2 -- class_3
  class_3 -- class_4
  class_4 -- class_5
