/**
 * walker — walks the repo files respecting `.gitignore`.
 *
 * SPEC §Phase 1: "respect for `.gitignore`". The `ignore` lib (npm) is the de
 * facto standard for parsing `.gitignore` in Node — same semantics as git.
 *
 * Always ignores (defense in depth, even without .gitignore):
 *   - node_modules/
 *   - .git/
 *   - .livewiki/
 *   - livewiki/            (the generated wiki itself — never indexed)
 *   - dist/
 *   - coverage/
 *
 * File selection is a DENYLIST, not an allowlist (SPEC §"Coverage ladder"):
 * every text file is walked; archives/binaries, media/fonts, source maps,
 * minified bundles, and known lockfiles are skipped. Files without an
 * extension are skipped (no meaningful language name). Extensions without a
 * tree-sitter grammar get `lang` = extension without the dot, lowercased
 * (`.rb` → `rb`) — tier-2 prose files, indexed with zero symbols.
 *
 * Output: paths RELATIVE to repoRoot with forward slashes (cross-platform).
 *
 * We do not follow symlinks: SPEC §Phase 1 says nothing about it and symlinks
 * in source code are rare. If one shows up, it will loop or error — which is
 * OK (a sign of a strange configuration the user needs to resolve).
 */

import * as nodeFs from "node:fs/promises";
import * as nodePath from "node:path";
import ignore from "ignore";

/** Languages with a tree-sitter grammar (tier 1). Extension → lang mapping. */
export const EXTENSION_LANG: Record<string, string> = {
  ".ts": "typescript",
  ".tsx": "tsx",
  ".js": "javascript",
  ".jsx": "tsx",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".py": "python",
  ".go": "go",
  ".rs": "rust",
  ".java": "java",
};

/**
 * Denylist: extensions that are never documentation input (archives,
 * binaries, media, fonts, source maps). Everything else is walked as text.
 */
export const DENIED_EXTENSIONS: ReadonlySet<string> = new Set([
  // archives/binaries
  ".zip", ".gz", ".tar", ".7z", ".rar", ".exe", ".dll", ".so", ".dylib",
  ".bin", ".dat", ".wasm", ".class", ".jar", ".pyc", ".pyo", ".o", ".a",
  // media/fonts
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg", ".mp4", ".mov",
  ".mp3", ".wav", ".pdf", ".ttf", ".otf", ".woff", ".woff2", ".eot",
  // source maps
  ".map",
]);

/**
 * Denylist: lockfiles skipped by exact basename (generated, huge, and never
 * documentation input). Compared case-insensitively.
 */
export const DENIED_BASENAMES: ReadonlySet<string> = new Set([
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "cargo.lock",
  "gemfile.lock",
  "poetry.lock",
  "go.sum",
  "composer.lock",
]);

/** Minified bundles are generated artifacts — never documentation input. */
function isMinified(nameLower: string): boolean {
  return nameLower.endsWith(".min.js") || nameLower.endsWith(".min.css");
}

export interface WalkOptions {
  /** Additional patterns to ignore (beyond .gitignore + defaults). */
  extraIgnores?: readonly string[];
}

export interface WalkResult {
  /** Path relative to repoRoot with forward slashes. */
  path: string;
  /** Language inferred from the extension. */
  lang: string;
}

/**
 * Builds the ignore filter combining .gitignore + defaults + extras.
 */
async function buildIgnore(repoRoot: string, opts: WalkOptions): Promise<ReturnType<typeof ignore>> {
  const ig = ignore();

  // Defaults — defense in depth in case .gitignore does not exist or does not
  // cover these paths (e.g. .livewiki/, which is generated by ourselves).
  ig.add([
    ".git/",
    "node_modules/",
    ".livewiki/",
    "livewiki/",
    "dist/",
    "coverage/",
  ]);

  // Try to load .gitignore from repoRoot. Silent failure if it does not exist.
  try {
    const gitignorePath = nodePath.join(repoRoot, ".gitignore");
    const content = await nodeFs.readFile(gitignorePath, "utf8");
    ig.add(content);
  } catch {
    // No .gitignore — defaults only.
  }

  if (opts.extraIgnores) {
    ig.add([...opts.extraIgnores]);
  }

  return ig;
}

/**
 * Recursively walks `repoRoot` and returns indexable files.
 *
 * Implementation: stack-based so the callstack does not blow up in deep repos.
 * Uses `readdir({ withFileTypes: true })` — a single call per directory.
 */
export async function walkRepo(
  repoRoot: string,
  opts: WalkOptions = {},
): Promise<WalkResult[]> {
  const ig = await buildIgnore(repoRoot, opts);
  const out: WalkResult[] = [];

  // Stack of directories to visit. Each entry is absolute.
  const stack: string[] = [repoRoot];

  while (stack.length > 0) {
    const dir = stack.pop()!;
    let entries;
    try {
      entries = await nodeFs.readdir(dir, { withFileTypes: true });
    } catch (err) {
      // Permission denied or directory vanished during the walk. Skip.
      // eslint-disable-next-line no-console
      console.warn(`[livewiki] walker: cannot read ${dir}: ${(err as Error).message}`);
      continue;
    }

    for (const entry of entries) {
      const abs = nodePath.join(dir, entry.name);
      const relFromRoot = nodePath.relative(repoRoot, abs);
      // ignore() operates on RELATIVE paths with forward slashes (even on Windows).
      const relPosix = relFromRoot.split(nodePath.sep).join("/");

      if (ig.ignores(relPosix)) continue;

      if (entry.isDirectory()) {
        stack.push(abs);
      } else if (entry.isFile()) {
        const nameLower = entry.name.toLowerCase();
        const ext = nodePath.extname(nameLower);
        if (ext === "") continue; // extensionless file — no meaningful lang
        if (DENIED_EXTENSIONS.has(ext)) continue;
        if (DENIED_BASENAMES.has(nameLower)) continue;
        if (isMinified(nameLower)) continue;
        // Grammar-mapped extensions keep their language name (tier 1);
        // everything else is tier-2 prose, lang = extension without the dot.
        const lang = EXTENSION_LANG[ext] ?? ext.slice(1);
        out.push({ path: relPosix, lang });
      }
      // symlinks and others: ignored (isFile/isDirectory=false). Documented
      // in the module header.
    }
  }

  // Stable order by path — eases diffing between runs and readability.
  out.sort((a, b) => a.path.localeCompare(b.path));
  return out;
}